version: "3.3"
services:
  proxy:
    ports:
      - "8060:80"

  backend:
    ports:
      - "8888:8888"
    volumes:
      - ./backend/app:/app
    build:
      context: ./backend
    command: /start-reload.sh

  frontend:
    build:
      context: ./client
    volumes:
      - ./client:/app
    ports:
      - "8070:80"

networks:
  default:
